# General application configuration
#----------------------------------------
# Configure GIT

git: 
  path: 'workspace/vobs'
  uri:
  user:
  password:

#Clear Case configraration
clear_case:
  view_name: 'vtrofymyuk_view1'
  view_location: 'm:'
  versions_input_folders: 
    - 'workspace/versions'
  
# Files to be ignored in import
ignore_list:
  - 'lost+found'
  - 'lost+found/**/*'
  - 'Release'
  - 'lost+found/**/*'
  - 'Release/**/*'
  - '.DS_Store'

test:
  git: 
    path: 'test/test_store/vobs'
    uri:
    user:
    password:

  #Clear Case configraration
  clear_case:
    view_name: 'vtrofymyuk1'
    view_location: 'test/mocks'
    user:
    password:
    
  # Files to be ignored in import



