# General application configuration
#----------------------------------------
# Configure GIT

git: 
  path: '../Workspace/vobs'
  uri:
  user:
  password:

#Clear Case configraration
clear_case:
  view_name: 'vtrofymyuk_view1'
  view_location: 'M:'
  versions_input_folders: 
    - 'workspace/versions'
  
# Files to be ignored in import
# IMPORTANT: 
# 1) Use UNIX style path separators ('/')
# 2) Use masks on the end of the path only ('/foleder/*.ext)
ignore_list:
  - 'lost+found/'
  - 'Release/'
  - '.DS_Store'

test:
  git: 
    path: 'test/test_store/vobs'
    uri:
    user:
    password:

  #Clear Case configraration
  clear_case:
    view_name: 'vtrofymyuk1'
    view_location: 'test/mocks'
    user:
    password:
    
  # Files to be ignored in import



