locations: 
- 'r:\Mcu_Ngp\Versions_7.X'
- 'r:\Mcu_Ngp\Versions_8.X'
- 'r:\Mcu_Ngp\Customer Support\Patches'
- 'r:\Mcu_Audio\Versions\Kepler\Software_Versions'
- 'r:\Mcu_Audio\Versions\MR1\Software_Versions'
- 'r:\Mcu_Audio\Versions\Alta\Software_Versions'
# main_version:
versions:
- 'mcu-7.1.2'
- 'mcu-7.2.2'
- 'mcu-7.5.0'
- 'mcu-7.5.1'
- 'ucgw-7.6.0'
- 'ucgw-7.6.5'
- 'ucgw-7.7.0'
- 'mcu-8.0.0'
- 'mcu-8.0.1'
- 'mcu-8.1.0'
- 'mcu-8.2.0'
- 'mcu-8.3.0'
- 'mcu-8.3.1'
- 'mcu-8.3.2'
- 'vcgw-8.3.2'

# customer_support:
- 'mcu-4.5.0'
- 'mcu-5.4.4'
- 'mcu-5.7.1'
- 'mcu-5.7.2'
- 'mcu-5.7.3'
- 'mcu-7.1.0'
- 'mcu-7.1.1'
- 'mcu-7.1.2'
- 'mcu-7.2.0'
- 'mcu-7.5.1'
- 'mcu-7.5.6'
- 'mcu-7.6.0'
- 'mcu-7.6.1'
- 'mcu-7.7.0'
- 'mcu-7.7.1'
- 'mcu-7.7.2'
- 'mcu-7.7.3'
- 'mcu-7.7.4'
- 'mcu-7.7.5'
- 'mcu-7.7.6'
- 'mcu-8.2.0'

# kepler:
- 'mcu-6.0'
- 'mcu-6.1'
- 'mcu-6.2'
- 'mcu-6.5'
